[dev]
    functions = "./functions"
    framework = "#custom"
    command = "npm run dev"
    targetPort = 5000

[build]
    command = "npm run build"
    framework = "#custom"
    functions = "./.netlify/functions"
    publish = "public"